### ISSUE TITLE
Cursor moving while in action mode

### ISSUE THREAD

**Issue by calaverinha** [mfoltz/RetroCamera#29]
When the game starts, action mode is working fine. But when I press the toggle button to move my cursor around, it eventually stops centering when I go back to action mode. And it's not like it retains the cursor position of the no-action camera (if this was the case I would just bring it to the center and problem solved), the cursor starts to move in my look direction IN action mode, basically turning action mode impossible to play. Maybe there is something to do with some camera settings, or offshoulder settings, IDK. But in the beggining, I need to toggle action mode on and off a lot to click "Claim", so eventually it will break, because cursor doesn't fix in the center anymore in action mode. 

I was testing this and the bugged action mode works like it was in the normal mode, like if I look top right, my vampire will aim in that direction. So I toggle it off, check cursor, and the cursor moved to top right. Toggle back to action, look top left, toggle back to normal, cursor is there, not centered. So I'm not sure if I'm doing something wrong. And, again, it seems to only bug when I toggle a lot. If I restart and toggle action and never toggle it off, it works as it should.

**Comment by AmericanEnglish** [comment]
I had this happen to me as well. I fixed it by restarting my computer but I have no idea how you would fix it otherwise.

**Comment by scourn** [comment]
Same thing, this happens whenever you use your C block ability. It causes the camera to bug out. Afterwards, your character is always at an angle when trying to fight.

**Comment by zeritox07** [comment]
can confirm it's still happening, sometimes it goes back to normal but unsure on how it happens.
